Develop/feature separation
OlyaMilch/py_test pull request #1
Opened 2024-04-21 15:36 UTC by OlyaMilch

2024-04-21 15:43 UTC, Pelmen323 commented
123

2024-04-21 15:45 UTC, Makentoshe requested changes

2024-04-21 15:45 UTC, Makentoshe commented on main.py
> +@app.route("/")
Useless functions, let's remove it for now

2024-04-21 15:45 UTC, Makentoshe commented on ingredients.py
> +
Redundant spaces

2024-04-21 15:45 UTC, Makentoshe commented on ingredients.py
> +    id = db.Column(db.Integer, primary_key=True)
Do we need `unique=True` for primary key?

2024-04-21 15:45 UTC, Makentoshe commented on 2app_and_dataframe.py
> +from flask import Flask, jsonify, request
Do we need this file at all? I suggest removing it if it is necessary for us right now

2024-04-21 19:48 UTC, OlyaMilch commented on ingredients.py
> +
fixed

2024-04-21 19:48 UTC, OlyaMilch commented on ingredients.py
> +    id = db.Column(db.Integer, primary_key=True)
fixed

2024-04-21 19:49 UTC, OlyaMilch commented on 2app_and_dataframe.py
> +from flask import Flask, jsonify, request
done

2024-04-21 19:53 UTC, OlyaMilch commented on main.py
> +@app.route("/")
don't fixed because 'db = SQLAlchemy(app)' used when importing into another file

2024-04-22 07:14 UTC, Makentoshe commented on main.py
> +@app.route("/")
It is not about 10 line, but about 13 line with useless "/" route

2024-04-22 09:50 UTC, Makentoshe commented on ingredients.py
> +    id = db.Column(db.Integer, primary_key=False)
I believe `id` __should__ be a primary key, because it is unique, and also should have `unique=True`

Also `category` and `title` shouldn't be unique values. For example, we may have 2 ingredients like carrot and potato, both of which are vegetables, so the `category` may be like `vegetable`

2024-04-22 10:21 UTC, OlyaMilch commented on ingredients.py
> +    id = db.Column(db.Integer, primary_key=False)
all set

2024-04-22 10:22 UTC, OlyaMilch commented on main.py
> +@app.route("/")
Fixed

2024-04-24 09:47 UTC, Makentoshe approved these changes

2024-04-24 17:01 UTC, merged