Recipe step
OlyaMilch/py_test pull request #6
Opened 2024-05-05 12:51 UTC by OlyaMilch

2024-05-06 11:57 UTC, Makentoshe requested changes
Not bad, let's remove comments with the questions

2024-05-06 11:57 UTC, Makentoshe commented on Recipe_step.py
> +class Recipe_step(db.Model):
Rename as corresponding to https://peps.python.org/pep-0008/#class-names

2024-05-06 11:57 UTC, Makentoshe commented on Recipe_step.py
> +    id_s = db.Column(db.Integer, unique=True, primary_key=True)  # ты хочешь id в str, но точно ли нам это надо?
Let's keep it integer then until the best times

2024-05-06 11:57 UTC, Makentoshe commented on Recipe_step.py
> +    id_s = db.Column(db.Integer, unique=True, primary_key=True)  # ты хочешь id в str, но точно ли нам это надо?
But then the `next step` and `prev step` also should be int
And rename 'em according to https://peps.python.org/pep-0008/#function-and-variable-names

2024-05-07 09:22 UTC, Makentoshe approved these changes

2024-05-07 11:06 UTC, OlyaMilch commented on Recipe_step.py
> +    id_s = db.Column(db.Integer, unique=True, primary_key=True)  # ты хочешь id в str, но точно ли нам это надо?
fixed

2024-05-07 11:06 UTC, OlyaMilch commented on Recipe_step.py
> +class Recipe_step(db.Model):
fixed

2024-05-07 11:06 UTC, merged