Separation branch
OlyaMilch/py_test pull request #8
Opened 2024-06-12 14:24 UTC by OlyaMilch

Moving all classes into separate files.
Create map () in the Pecipe.py

2024-06-14 16:22 UTC, Makentoshe requested changes
Remove class_ prefix for .py files.

2024-06-14 16:22 UTC, Makentoshe commented on ingredients.py
> +from class_NetworkIngredient import *
move imports to the top

2024-06-14 16:22 UTC, Makentoshe commented on Recipe.py
> +from class_NetworkRecipe import *
Move imports to the top

2024-06-14 18:32 UTC, Pelmen323 commented
Why do you use the dot symbol in commit names? As for me, it looks odd

2024-06-14 18:35 UTC, Pelmen323 commented on class_IngredientToNetworkIngredientMapper.py
> +        return NetworkIngredient(ingredient.id_i, ingredient.title, ingredient.category)  # возвращает созданный объект
Add an empty line to the end of the file, you can see here that github also hints that

2024-06-14 18:38 UTC, Pelmen323 commented on class_IngredientToNetworkIngredientMapper.py
> +from class_NetworkIngredient import *
Why do we use star imports?

2024-06-14 18:39 UTC, Pelmen323 commented on class_IngredientToNetworkIngredientMapper.py
> +class IngredientToNetworkIngredientMapper:
Add a space between class and import

2024-06-14 19:15 UTC, Pelmen323 commented on ingredients.py
> +    else:
why do we need 'else' here?

2024-06-18 14:36 UTC, OlyaMilch commented on ingredients.py
> +from class_NetworkIngredient import *
fixed

2024-06-18 14:36 UTC, OlyaMilch commented on Recipe.py
> +from class_NetworkRecipe import *
fixed

2024-06-18 14:37 UTC, OlyaMilch commented on class_IngredientToNetworkIngredientMapper.py
> +from class_NetworkIngredient import *
fixed

2024-06-18 14:37 UTC, OlyaMilch commented on class_IngredientToNetworkIngredientMapper.py
> +class IngredientToNetworkIngredientMapper:
fixed

2024-06-18 14:37 UTC, OlyaMilch commented on class_NetworkIngredient.py
> +import json
fixed

2024-06-18 14:37 UTC, OlyaMilch commented on ingredients.py
> +    else:
delete

2024-06-20 19:38 UTC, OlyaMilch commented on ingredientmapper.py
all renamed

2024-06-20 19:38 UTC, merged